### PR TITLE
Added "Folding", 3D shape now changes on slider, loads of bugs introduced and dealt with

### LINKED ISSUE #17: Bugs
Axiom 3 doesn't work (diagonal-unfolded)
Selecting lines on right or bottom (diagonal unfolded) doesn't work, parsing is broken

Axiom 2 doesn't work (flatsheet-noframe, top left, bottom right selected)

### LINKED ISSUE #19: Bugs when folding a square in half
It seems to get the wrong selected line to use as the axis of rotation, and seems to get the wrong points to rotate.

### LINKED ISSUE #20: Axiom 3 doesn't work with 2 perpendicular lines
title

### PR DESCRIPTION
**Pull request by jgao222**
Add the folding functionality. Added new files to test on.

Fixed a slew of issues related to re-rendering, and a function that was causing bugs. Fixes #17 and partially addresses #14

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -856,7 +1064,82 @@ function main() {
...
+     */
+    function enforce3DCoordinates(pointList) {
+        let outArray = [];
+        for (let i = 0; i < pointList.length; i++) {
+            let point = pointList[i];
+            if (point.length === 2) {
+                outArray = outArray.concat(point);
+                outArray.push(0);
+            } else if (point.length === 4) {
+                point.pop();
```
Comment (sstadnicki) [inline main.js]: I think you want this to be outArray.pop() and put it after the next call; while length-4 points are unlikely to come up (I think), this would modify the array passed in if it had any, and I'm pretty sure that's not what you want to do.

**Review by sstadnicki — APPROVED** [review]
Looks generally good modulo the one change I mentioned.

**Comment by jgao222** [comment]
Note that since the SVG is now subdivided and re-rendered from the FOLD object on every single new edge creation, creating and edge that intersects another will result in neither edge being entirely foldable. Edges also disappear if not folded and a new edge is created.
